language: go

env: 
    - GO111MODULE=on

go:
    - 1.17.x
    - 1.18.x

git:
    depth: 1

before_install:
    - cd dyndns

script:
    - go test -v ./...
    - go build ./...

notifications:
    email:
        on_success: never
        on_failure: always
